### ISSUE TITLE
Installing multiple packages

### ISSUE THREAD

**Issue by clancy** [VGBenjamin/PackageInstaller#3]
I am trying to install multiple packages one after another from a powershell script.

Using the following:

```
$packageCommand = "$($path)\Sidewalk.PackageInstaller\Sidewalk.SC.PackageInstaller.Client.exe"
Get-ChildItem -Path SitecoreModule -File | Foreach `
{
    $packageArguments = " -sitecoreUrl `"http://sitecore`" -sitecoreDeployFolder `"C:\Sitecore\Website`" -packagePath `"$($_.fullname)`" -connector `"sitecore`" " 
    Start-Process -FilePath $packageCommand -ArgumentList $packageArguments -Wait -NoNewWindow `    
}
Write-Host "Installed Sitecore packages"
```

However it seems that every second one is failing due to a timeout.

I assume this is a result of a restart after each module is installed.

Is there any way to stop the restart or should I manage the wait from my powershell script?

Awesome work btw.

**Comment by VGBenjamin** [comment]
Hello,

I have write a post on my blog to give you an alternative to install your folder: http://sitecoreblog.blogspot.be/2016/06/scan-and-install-all-packages-in-folder.html
With this technique you can install the packages and be sure that those packages are installaed only once. 

But I am not sure at all that it will fix your issue. 
I didn't have the time to really investigate a workaround right now but you can take a look in the class Sidewalk.SC.PackageInstaller.Service.SitecorePackageInstaller. This is the code executed in the sitecore context. 
If you install a .zip package the methode is InstallPackage. If it is a .update: InstallTdsPackage

For the .update I really don't see any options to wait the reboot before returning to the console. But for the .zip. You could probably add an other aspect. (I didn't have found this kind of code in the sitecore's code to install)

**Comment by VGBenjamin** [comment]
If I understand correctly the way the Sitecore's way of doing it, they didn't really have the issue because to display the result page the iis need to be allready recycled. So they didn't have the issue. 
A simple workaround then could be to just add a Webrequest on the homepage for example an wait until you have a response. You can do that in the InstallPAge method or in your powershell both should do the trick. 

In powerhsell you can do that via this command:
Invoke-WebRequest -Uri $uri
